;;; ts-overrides-theme.el --- My theme overrides

;;; Code:

(deftheme ts-overrides
  "Custom theme overrides.")

(custom-theme-set-faces
 'ts-overrides
 '(default ((t (:foreground "gray85" :background nil))))
 ;; '(default ((t (:foreground "gray85" :background "#242730"))))
 '(fringe ((t (:background "#1B2B32"))))
 '(cursor ((t (:background "#51afef"))))
 '(line-number-current-line ((t (:foreground "#fac863" :background "#3d5958" :weight bold))))
 '(line-number ((t (:foreground "#f3f4f6" :background "#2d4040"))))
 '(highlight ((t (:background "#3d5958" :foreground nil))))
 '(region ((t (:background "#338f86" :foreground "#f3f4f6"))))
 '(flycheck-fringe-error ((t (:foreground "systemRedColor"))))
 '(flycheck-fringe-warning ((t (:foreground "DarkGoldenrod2"))))
 '(flycheck-fringe-info ((t (:foreground "#74af68"))))
 '(mode-line ((t (:background "#242730" :foreground "#f3f4f6" :box nil))))
 '(powerline-inactive2 ((t (:background "gray11"))))
 '(spaceline-evil-emacs ((t (:background "#cc99cc" :foreground "#3E3D31" :inherit 'mode-line))))
 '(spaceline-evil-normal ((t (:background "DarkGoldenrod2" :foreground "#3E3D31" :inherit 'mode-line))))
 '(spaceline-evil-visual ((t (:background "#338f86" :foreground "#fac863" :inherit 'mode-line))))
 '(spaceline-evil-insert ((t (:background "#74af68" :foreground "#3E3D31" :inherit 'mode-line))))
 '(show-paren-match ((t (:foreground: nil :background "white"))))
 '(helm-selection ((t (:background "#3d5958" :weight bold))))
 '(helm-source-header ((t (:background nil :foreground "#fac863" :weight bold :height 1.1 :family "Menlo"))))
 '(helm-visible-mark ((t (:background "#ffbd29" :foreground "black"))))
 '(helm-candidate-number ((t (:background "#ffbd29" :foreground "black"))))
 '(helm-buffer-directory ((t (:background "#5d7978" :foreground "##fac863"))))
 '(helm-header ((t (:background "#5d7978" :foreground "##fac863"))))
 '(helm-ff-file ((t (:background nil :foreground "gray80"))))
 '(helm-ff-directory ((t (:background nil :foreground "#6699cc"))))
 '(helm-ff-executable ((t (:background nil :foreground "#74af68"))))
 '(helm-ff-dotted-directory ((t (:background nil :foreground "#6699cc"))))
 '(helm-ff-prefix ((t (:background "#ffbd29" :foreground "#fac863"))))
 '(company-tooltip ((t :inherit default :background "#3d5958")))
 '(company-scrollbar-bg ((t :background "#232526")))
 '(company-scrollbar-fg ((t :background "#338f86")))
 '(company-tooltip-selection ((t :background "#5d7978")))
 '(company-tooltip-common ((t :inherit font-lock-constant-face)))
 '(company-tooltip-annotation ((t (:foreground "#fae683"))))
 '(org-todo ((t (:bold t :weight bold :foreground "#ec5f67"))))
 '(org-done ((t (:bold t :weight bold :foreground "#74af68"))))
 '(org-headline-done ((t (:foreground "#5d7978" :strike-through nil))))
 '(org-level-1 ((t (:height 1.1 :inherit 'outline-1 :foreground "#dbe2ef"))))
 '(org-level-2 ((t (:inherit 'outline-2 :foreground "#5fb3b3"))))
 '(org-level-3 ((t (:inherit 'outline-3 :foreground "#fac863"))))
 '(org-level-4 ((t (:inherit 'outline-2 :foreground "#74af68"))))
 '(org-ellipsis ((t (:underline nil))))
 '(org-archived ((t (:underline t))))
 '(org-ellipsis ((t (:underline nil :background nil))))
 '(org-verbatim ((t (:foreground "#65737e"))))
 '(org-hide ((t (:foreground "#2a2e38"))))
 '(org-block ((t (:foreground "gray85"))))
 '(font-lock-comment-face ((t (:foreground "#65737e"))))
 '(font-lock-function-name-face ((t (:foreground "#6699cc"))))
 '(font-lock-string-face ((t (:foreground "#74af68"))))
 '(solaire-default-face ((t (:inherit 'default :background "#2a2e38"))))
 '(tide-hl-identifier-face ((t (:foreground "#fac863"))))
 '(js2-object-property ((t (:foreground "white"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#6699cc"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#ec5f67"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#74af68"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#ffbd29"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#cc99cc"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#fae683"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#338f86"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "red" :weight bold :inverse-video t))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit 'rainbow-delimiters-unmatched-face))))
 )

;;; ts-overrides-theme.el ends here
