;;; ts-overrides-theme.el --- My theme overrides

;;; Code:

(deftheme ts-overrides
  "Custom theme overrides.")

(custom-theme-set-faces
 'ts-overrides
 '(default ((t (:foreground "#ebf2ff" :background "#242730"))))
 ;; '(default ((t (:foreground "gray90" :background "#1B2B32"))))
 '(fringe ((t (:background "#1B2B32"))))
 '(cursor ((t (:background "#51afef"))))
 '(line-number-current-line ((t (:foreground "#ebf2ff" :background "#3d5958" :weight bold))))
 '(line-number ((t (:background "#2d4040"))))
 '(highlight ((t (:background "#3d5958" :foreground nil))))
 '(region ((t (:background "#338f86" :foreground "#ebf2ff"))))
 '(flycheck-fringe-error ((t (:foreground "systemRedColor"))))
 '(flycheck-fringe-warning ((t (:foreground "DarkGoldenrod2"))))
 '(flycheck-fringe-info ((t (:foreground "#74af68"))))
 '(mode-line ((t (:background "#3d5958" :foreground "#ebf2ff" :box nil))))
 '(spaceline-evil-emacs ((t (:background "#3E3D32" :foreground "#3E3D31" :inherit 'mode-line))))
 '(spaceline-evil-normal ((t (:background "DarkGoldenrod2" :foreground "#3E3D31" :inherit 'mode-line))))
 '(spaceline-evil-visual ((t (:background "#338f86" :foreground "#ebf2ff" :inherit 'mode-line))))
 '(spaceline-evil-insert ((t (:background "#74af68" :foreground "#3E3D31" :inherit 'mode-line))))
 '(show-paren-match ((t (:foreground: "#2d2d2d" :background "#cc99cc"))))
 '(helm-selection ((t (:background "#3d5958" :weight bold))))
 '(helm-source-header ((t (:background nil :foreground "#ebf2ff" :weight bold :height 1.1 :family "Menlo"))))
 '(helm-visible-mark ((t (:background "#ffbd29" :foreground "black"))))
 '(helm-candidate-number ((t (:background "#ffbd29" :foreground "black"))))
 '(helm-buffer-directory ((t (:background "#5d7978" :foreground "#ebf2ff"))))
 '(helm-header ((t (:background "#5d7978" :foreground "#ebf2ff"))))
 '(helm-ff-file ((t (:background nil :foreground "gray80"))))
 '(helm-ff-directory ((t (:background nil :foreground "#6699CC"))))
 '(helm-ff-executable ((t (:background nil :foreground "#74af68"))))
 '(helm-ff-dotted-directory ((t (:background nil :foreground "#6699CC"))))
 '(helm-ff-prefix ((t (:background "#ffbd29" :foreground "#ebf2ff"))))
 '(company-tooltip ((t :inherit default :background "#3d5958")))
 '(company-scrollbar-bg ((t :background "#232526")))
 '(company-scrollbar-fg ((t :background "#338f86")))
 '(company-tooltip-selection ((t :background "#5d7978")))
 '(company-tooltip-common ((t :inherit font-lock-constant-face)))
 '(org-todo ((t (:bold t :weight bold :foreground "#EC5f67"))))
 '(org-done ((t (:bold t :weight bold :foreground "#74af68"))))
 '(org-headline-done ((t (:foreground "#5d7978" :strike-through nil))))
 '(org-level-1 ((t (:height 1.1 :inherit 'outline-1 :foreground "#ebf2ff"))))
 '(org-level-2 ((t (:inherit 'outline-2 :foreground "#5FB3B3"))))
 '(org-level-3 ((t (:inherit 'outline-3 :foreground "#FAC863"))))
 '(org-level-4 ((t (:inherit 'outline-2 :foreground "#74af68"))))
 '(org-ellipsis ((t (:underline nil))))
 '(org-archived ((t (:underline t))))
 '(org-ellipsis ((t (:underline nil :background nil))))
 '(org-verbatim ((t (:foreground "#65737E"))))
 '(font-lock-comment-face ((t (:foreground "#65737E"))))
 '(font-lock-string-face ((t (:foreground "#74af68"))))
 '(solaire-default-face (( t (:inherit 'default :background "#2a2e38"))))
 )

;;; ts-overrides-theme.el ends here
